[project]
name = "enterprice-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-adk>=1.16.0",
    "langchain>=1.0.2",
    "langchain-community>=0.4",
    "langgraph>=1.0.1",
    "pgvector>=0.4.1",
    "psycopg>=3.2.10",
]
